name: Deploy Project
on: "push"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: actions/checkout@v3
      - name: install_node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install_dependencies
        run: npm ci
      - name: run_tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get_code
        uses: actions/checkout@v3
      - name: install_node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install_dependencies
        run: npm ci
      - name: run_tests
        run: npm test
      - name: build
        run: npm run build
      - name: complete
        run: echo "Done"